# Copyright (C) 2022 Nitrokey GmbH
# SPDX-License-Identifier: CC0-1.0

include: 'https://raw.githubusercontent.com/Nitrokey/common-ci-jobs/master/common_jobs.yml'

stages:
  - pull-github
  - build
  - deploy

variables:
  GIT_STRATEGY: clone
  GIT_DEPTH: 0
  GIT_SUBMODULE_STRATEGY: recursive
  REPO_NAME: opcard-rs
  MAIN_BRANCH: main
  COMMON_PULL: "true"
  COMMON_UPLOAD_NIGHTLY: "false"
  COMMON_GITHUB_RELEASE: "false"
  COMMON_UPLOAD_FILES: "false"

build:
  image: registry.git.nitrokey.com/nitrokey/opcard-rs/opcard-rs-build:latest
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - if: '$CI_PIPELINE_SOURCE == "web"'
  tags:
    - docker
  stage: build
  script:
    - make ci
  after_script:
    - cp /app/.cache/scdaemon.log scdaemon.log
    - wget $icon_server/checkmark/$CI_COMMIT_REF_NAME/$CI_COMMIT_SHA/$CI_JOB_NAME/$CI_JOB_STATUS/${CI_JOB_URL#*/*/*/}
  coverage: '/^\d+.\d+% coverage/'
  artifacts:
    paths:
      - "scdaemon.log"
      - "cobertura.xml"
      - "tarpaulin-report.html"
    reports:
      coverage_report:
        coverage_format: cobertura
        path: cobertura.xml
