# Copyright (C) 2022 Nitrokey GmbH
# SPDX-License-Identifier: CC0-1.0

[package]
name = "opcard"
version = "0.1.0"
authors = ["Robin Krahl <robin@nitrokey.com>"]
edition = "2021"
description = "OpenPGP smart card implementation"
repository = "https://github.com/nitrokey/opcard-rs"
license = "LGPL-3.0-only"

[[example]]
name = "virtual"
required-features = ["virtual"]

[dependencies]
heapless = "0.7"
heapless-bytes = "0.3"
iso7816 = "0.1"
log = "0.4"
serde = { version = "1.0", default-features = false }
subtle = { version = "2.4.1", default-features = false }
trussed = "0.1.0"

# optional dependencies
apdu-dispatch = { version = "0.1", optional = true }
vpicc = { version = "0.1.0", optional = true }

[dev-dependencies]
env_logger = "0.9"
openpgp-card = "0.2.7"
stoppable_thread = "0.2.1"
test-log = "0.2.10"
trussed = { version = "0.1.0", features = ["virt"] }

[features]
std = []
virtual = ["std", "vpicc"]

[patch.crates-io]
trussed = { git = "https://github.com/trussed-dev/trussed" }

[package.metadata.docs.rs]
all-features = true
