# Copyright (C) 2022 Nitrokey GmbH
# SPDX-License-Identifier: CC0-1.0

[package]
name = "opcard"
version = "0.1.0"
authors = ["Nitrokey GmbH <info@nitrokey.com>"]
edition = "2021"
description = "OpenPGP smart card implementation"
repository = "https://github.com/nitrokey/opcard-rs"
license = "LGPL-3.0-only"

[workspace]
members = [
	"fuzz"
]

[[example]]
name = "virtual"
required-features = ["virtual"]

[dependencies]
heapless = "0.7"
heapless-bytes = "0.3"
iso7816 = "0.1.1"
log = "0.4"
serde = { version = "1.0", default-features = false }
subtle = { version = "2.4.1", default-features = false }
trussed = "0.1.0"
serde_repr = "0.1"
hex-literal = "0.3.4"

# optional dependencies
apdu-dispatch = { version = "0.1", optional = true }
delog = { version = "0.1.5", optional = true }
vpicc = { version = "0.1.0", optional = true }

[dev-dependencies]
env_logger = "0.9"
openpgp-card = "0.2.7"
openpgp-card-sequoia = "0.0.15"
sequoia-openpgp = "1.10.0"
openpgp-card-pcsc = "0.2.1"
regex = "1.6.0"
stoppable_thread = "0.2.1"
test-log = "0.2.10"
trussed = { version = "0.1.0", features = ["virt"] }

[features]
std = []
virtual = ["std", "vpicc"]

# used for delog
log-all = []
log-none = []
log-info = []
log-debug = []
log-warn = []
log-error = []

[patch.crates-io]
trussed = { git = "https://github.com/trussed-dev/trussed" , rev = "3da56d8e41b9de64b852ed2bdcfd623118b09c3d" }
littlefs2-sys = { git = "https://github.com/sosthene-nitrokey/littlefs2-sys.git", branch = "bindgen-runtime-feature" }

[package.metadata.docs.rs]
all-features = true
