# Copyright (C) 2022 Nitrokey GmbH
# SPDX-License-Identifier: CC0-1.0

[package]
name = "opcard"
version = "0.1.0"
authors = ["Robin Krahl <robin@nitrokey.com>"]
edition = "2021"
description = "OpenPGP smart card implementation"
repository = "https://github.com/nitrokey/opcard-rs"
license = "LGPL-3.0-only"

[[example]]
name = "virtual"
required-features = ["backend-software", "virtual"]

[dependencies]
heapless = "0.7"
iso7816 = "0.1"
log = "0.4"
serde = { version = "1.0", default-features = false }
subtle = { version = "2.4.1", default-features = false }

# optional dependencies
apdu-dispatch = { version = "0.1", optional = true }
trussed = "0.1.0"
vpicc = { version = "0.1.0", optional = true }
rand = { version = "0.8.5", optional = true }
rand_chacha = { version = "0.3.1", optional = true }
littlefs2 = { version = "0.3", optional = true }
interchange = { version = "0.2.1", optional = true }
lazy_static = { version = "1.4.0", optional = true }

[dev-dependencies]
env_logger = "0.9"
openpgp-card = "0.2.7"
stoppable_thread = "0.2.1"
test-log = "0.2.10"

[features]
std = []
virtual = ["std", "vpicc"]
backend-software = ["rand", "rand_chacha", "littlefs2", "interchange", "lazy_static"]

[package.metadata.docs.rs]
all-features = true
