[package]
name = "opcard"
version = "0.1.0"
authors = ["Robin Krahl <robin@nitrokey.com>"]
edition = "2021"
description = "OpenPGP smart card implementation"
repository = "https://github.com/nitrokey/opcard-rs"
license = "LGPL-3.0-only"

[[example]]
name = "virtual"
required-features = ["backend-software", "virtual"]

[dependencies]
heapless = "0.7"
iso7816 = "0.1"
log = "0.4"

# optional dependencies
apdu-dispatch = { version = "0.1", optional = true }
trussed = { version = "0.1.0", optional = true }
vpicc = { git = "ssh://git@github.com/Nitrokey/vpicc-rs.git", optional = true }

[dev-dependencies]
env_logger = "0.9"

[features]
std = []
virtual = ["std", "vpicc"]

# backends
backend-software = ["std"]
backend-trussed = ["trussed"]

[package.metadata.docs.rs]
all-features = true
